config/routes.rb
Rails.application.routes.draw do
  #homepage route
  root "sessions#welcome"
  #omniauth callback route
  match '/auth/github/callback', to: 'users#omniauth', via: [:get, :post]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #signup route
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  #logout route
  get '/logout' => 'sessions#destroy'


  resources :ratings

  resources :books do
    resources :ratings, only: [:index, :new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :ratings
  has_many :users, through: :ratings
  accepts_nested_attributes_for :ratings

  validates :title, :author, :publisher, :genre, :release_year, presence: true

  def self.book_list # helper_method :book_list
    @books = []

    Book.all.each do |book|
      @book_info = [book.title, book.id]
      @books << @book_info
    end
    @books
  end

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :title, presence: true
  validates :content, presence: true
  validates :score, numericality: {greater_than_or_equal_to: 1}, presence: true
  validates :score, numericality: {less_than_or_equal_to: 10}, presence: true
  validates :score, numericality: true

  scope :ordered_by_score, -> {order(score: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings
  has_many :books, through: :ratings
  has_secure_password
  validates :email, presence: true

  def self.create_from_omniauth(auth)
      User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
          u.name = auth[:info][:name]
          u.username = auth[:info][:nickname]
          u.email = auth[:info][:email] || auth[:info][:nickname]
          u.password = SecureRandom.hex(16)
      end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RatingsHelper
  # gives access to the views
  helper_method :current_user, :logged_in?
  before_action :require_login

  def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path
      end
  end

  def current_user
      #we don't use @user because it might override the user
      # variable in the controller
      # 1. if there is a session[:user_id] proceed..
      # ....(we don't want to make a call to the database
      # & not find anything)
      # 2. if @current_user already exists then set the user to @current_user
      # 3. if not, find user by user_id in the users table and set
      # to @current_user.
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
      current_user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @book.ratings.build
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @rating = Rating.new

    if @book.nil?
      redirect_to :action => :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :genre, :release_year)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, :redirect_if_not_logged_in
  before_action :set_rating, :require_user_access, only: [:edit, :update, :destroy]

  def index
    if params[:book_id] && @book = Book.find_by_id(params[:book_id])
      @ratings = @book.ratings.ordered_by_score
    else
      @ratings = Rating.all.ordered_by_score
    end
  end

  def show
    @rating = Rating.find_by_id(params[:id])
  end

  def new
    if params[:book_id] && @book = Book.find_by_id(params[:book_id])
      @rating = @book.ratings.new
    else
      @books = Book.book_list
      @rating = Rating.new
    end
  end

  def create
    @rating = current_user.ratings.build(rating_params)
    @rating.book_id = params[:book_id] || @rating.book_id = params[:rating][:book_id]
    if @rating.save
      redirect_to book_path(@rating.book)
    else
      @book = Book.find_by_id(params[:book_id]) if params[:book_id]
      @books = Book.book_list
      flash[:message] = @rating.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @rating = Rating.find(params[:id])
    @books = Book.book_list
  end

  def update
    if logged_in?
      @rating = Rating.find(params[:id])
      @rating.update(rating_params)
      flash[:success] = "Updated!"
      redirect_to rating_path(@rating)
    else
      flash[:message] = @rating.errors.full_messages.join(", ")
      render action: :edit
    end
  end

  def destroy
    @rating = current_user.ratings.find(params[:id])
    @rating.destroy
    redirect_to ratings_path
    flash[:notice] = "Deleted!"
  end

  private

  def rating_params
    params.require(:rating).permit(:title, :content, :score, :book_id, :user_id) 
  end
  def require_user_access
    unless @current_user == @rating.user
      flash[:error] = "Sorry, Access Denied."
      redirect_to user_path(current_user)
    end
  end
  def set_rating
    @rating = Rating.find_by(id: params[:id])
  end
  def redirect_if_not_logged_in
    redirect_to '/' if !logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:welcome, :new, :create]

  def welcome
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) # authenticate method comes from has_secure_password
      session[:user_id] = user.id # logs in a user
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid credentials, please try again!"
      redirect_to '/login'
    end
  end

  def omniauth
    #find or create a user using the attributes auth
    user = User.create_from_omniauth(auth)
    if user.valid?
      session[:user_id] = user.id
      redirect_to new_rating_path
    else
      flash[:message] = user.errors.full_messages.join("")
      redirect_to ratings_path
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :omniauth, :create]

  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    # redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  def omniauth
    #find or create a user using the attributes auth
    user = User.create_from_omniauth(auth)
    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid Entry, please try again!"
      redirect_to login_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end

  def require_user_access
    user = User.find_by(id: params[:id])
    unless current_user == user
      flash[:error] = "Sorry, Access Denied."
      redirect_to user_path(user)
    end
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_bar
    menu = ''
    if logged_in?
      menu << '<a href="' + user_path(current_user.id) + '">Profile</a>&nbsp'
      menu << '<a href="' + books_path + '">Books</a>&nbsp'
      menu << '<a href="' + ratings_path + '">Ratings</a>&nbsp'
      menu << '<a href="' + logout_path + '">Logout</a>&nbsp'
    end
    menu.html_safe
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def rating_form_header(f)
    out = ''
    if @book
      out << 'Book: ' + @book.title
    else
      out << (f.label  'Book:')
      out << (f.select :book_id, @books)
    end
    out.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if @ratings.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:
    </h2>

    <ul>
      <%= @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_frame.html.erb
<%= form_for([@book, @rating]) do |f| %>
<br>
  <%= rating_form_header(f) %><br><br>
  <%= f.label "Rating Title:"%>
  <%= f.text_field :title %><br><br>

  <%= f.label "Rating Score:"%>
  <%= f.number_field :score %><br><br>

  <%= f.label "Content:" %>
  <p><%= f.text_area :content %></p>
  <br>

  </p>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Books</h1>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :author %>
  <%= f.text_field :author %><br>
  <%= f.label :publisher %>
  <%= f.text_field :publisher %><br>
  <%= f.label :genre %>
  <%= f.text_field :genre %><br>
  <%= f.label :score %>
  <%= f.text_field :score %><br>
  <%= f.label :release_year %>
  <%= f.text_field :release_year %><br>
  <%= f.submit %>

<% end %>

app/views/books/index.html.erb
<h1> Books Index </h1>
<%= link_to "Create a Book", new_book_path %>
<% @books.each do |book| %>
  <ol>
    Title: <%= link_to book.title, book %><br>
    Author: <%= book.author %><br>
    Publisher: <%= book.publisher %><br>
    Genre: <%= book.genre %><br>
    Released: <%= book.release_year %><br>
  </ol>
-------------------------------------------------------------------------------------------------------
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@book) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :author %>
  <%= f.text_field :author %><br>
  <%= f.label :publisher %>
  <%= f.text_field :publisher %><br>
  <%= f.label :genre %>
  <%= f.text_field :genre %><br>
  <%= f.label :release_year %>
  <%= f.text_field :release_year %><br>
  <%= f.submit %>

<% end %>

app/views/books/show.html.erb
<h1>Books Show</h1>

Title: <%= @book.title %> <br>

Author: <%= @book.author %><br>

Publisher: <%= @book.publisher %><br>

Genre: <%= @book.genre %><br>

Released: <%= @book.release_year %><br><br>

<h2>New Rating</h2>

<%= form_for([@book, @rating]) do |f| %>
  <%= f.label "Rating Title:"%>
  <%= f.text_field :title %><br><br>

  <%= f.label "Rating Score:"%>
  <%= f.number_field :score %><br><br>

  <%= f.label "Content:" %>
  <p><%= f.text_area :content %></p>
  <br>

  </p>
  <%= f.submit "Create Rating" %>

<% end %>

<h2>All Ratings</h2>
<%= render 'ratings/rate' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= nav_bar %>
    <%= yield %>
  </body>
</html>

app/views/ratings/_error_message.html.erb
<% if @ratings.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:
    </h2>

    <ul>
      <%= @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/ratings/_form.html.erb
<%= form_for([@book, @rating]) do |f| %>
<br>
  <%= rating_form_header(f) %><br><br>
  <%= f.label "Rating Title:"%>
  <%= f.text_field :title %><br><br>

  <%= f.label "Rating Score:"%>
  <%= f.number_field :score %><br><br>

  <%= f.label "Content:" %>
  <p><%= f.text_area :content %></p>
  <br>

  </p>
  <%= f.submit %>
<% end %>

app/views/ratings/_rate.html.erb
<% if @book %>
  <ul>
  <% @book.ratings.ordered_by_score.each do |rating| %>
    Rating Title: <%= rating.title %><br>
    Book Info: <%= link_to rating.book.title, book_path(rating.book_id) %><br>
    Rating Author: <%= rating.user.username %><br>
    Rating Score: </b> <%= link_to rating.score, rating_path(rating.id) %><br>
  -------------------------------------------------------------------------------------------------------
  <br>
  <% end %>
  </ul>
<% else %>
  <ul>
  <br>
  <% @ratings.each do |rating| %>
    Rating Title: <%= rating.title %><br>
    Book Info: <%= link_to rating.book.title, book_path(rating.book_id) %><br>
    Rating Author: <%= rating.user.username %><br>
    Rating Score: </b> <%= link_to rating.score, rating_path(rating.id) %><br>
  -------------------------------------------------------------------------------------------------------
  <br>
  <% end %>
  </ul>
<% end %>

app/views/ratings/edit.html.erb
<h1>Edit your Rating</h1>
<%= render 'error_message' %>
<%= render 'form',  rating: @rating %>

app/views/ratings/index.html.erb
<h1>All Ratings</h1>
<%= render 'rate' %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>
<%= render 'error_message' %>
<%= render 'form' %>

app/views/ratings/show.html.erb
<h1><%= @rating.book.title %></h1>

<div>
  By: <%= @rating.user[:username] %><br>
  Title: <%= @rating.title %><br>
  Score: <%= @rating.score %><br>
  Content: <p><%= @rating.content %></p>
  <br>
</div>


<% if current_user == @rating.user %>
    <%= link_to "Edit Rating", edit_rating_path(@rating) %> |
    <%= link_to "Delete", @question, method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/shared/_error.html.erb
<% flash.each do |type, msg| %>
  <div class="field_with_error" style="width: 320px">
    <ul>
      <li><%= msg %></li>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>User Login</h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.submit %>
<% end %>
  

app/views/users/new.html.erb
<h1>Register Here!</h1>

<%= form_with(model: @user, url:'/signup', local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br><br><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br><br>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br><br>
  <%= f.submit "Sign Up"%>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.name %></h1>
Username: <%= current_user.username %><br>
Email: <%= current_user.email %><br>

Ratings: <%= current_user.ratings.count %>

<br><br>

<% current_user.ratings.ordered_by_score.each do |rating| %>
    <br><br>
    <b>Rating Title:</b> <%= rating.title %>
    <br>
    <b>Book Title:</b> <%= link_to rating.book.title, book_path(rating.book_id) %>
    <br>
    <b>Content: </b> <%= rating.content %>
    <br>
    <b>Rating Score: </b> <%= link_to rating.score, rating_path(rating.id) %>
    <br><br>
    -------------------------------------------------------------------------------------------------------
<% end %>